#!/usr/bin/env bash
#MISE description="Build the project"
bun build ./src/index.ts --outdir dist --target bun --external tree-sitter --external tree-sitter-rust

# Generate type definitions
bunx tsc --project tsconfig.build.json