#!/usr/bin/env bash
#MISE description="Build the project"
bun build ./src/index.ts --outdir dist --target bun

# Fix tree-sitter binary for Bun
./scripts/fix-tree-sitter.sh

# Generate type definitions
bunx tsc --project tsconfig.build.json